name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'deminy/docker-delayed-http-response' }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Docker Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: deminy/delayed-http-response

      -
        name: Image Digest of deminy/delayed-http-response:${{ steps.params.outputs.docker_tag }}
        run: echo ${{ steps.docker_build.outputs.digest }}
